services:

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  godns:
    image: timothyye/godns:2.9.4
    container_name: godns
    volumes:
      - ./godns/config.json:/config.json
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    environment:
      - WG_HOST=$WG_HOST
      - PASSWORD_HASH=$WG_PASSWORD_HASH
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    volumes:
      - "./wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    environment:
      - WEBPASSWORD=$PIHOLE_PASSWORD
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

  diun:
    image: crazymax/diun:4
    container_name: diun
    command: serve
    environment:
      - TZ=$TZ
      - LOG_LEVEL=info
      - LOG_JSON=false
    volumes:
      - "./diun:/data"
      - "./diun/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:2.11.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - URL=$SWAG_URL
      - SUBDOMAINS=$SWAG_SUBDOMAINS
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - "./swag:/config"
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.4

  firefox:
    image: jlesage/firefox:v24.08.1
    container_name: firefox
    restart: unless-stopped
    ports:
      - "5800:5800/tcp"
      - "5900:5900/tcp"
    environment:
      - TZ=$TZ
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
    volumes:
      - "./firefox:/config:rw"

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
